services:
  db:
    image: postgres:16
    container_name: vendors-hub-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vendors
      POSTGRES_PASSWORD: vendors_pass
      POSTGRES_DB: vendors_hub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
